---
title: "About Me"
sidebar: false 
---

# *Education*

-   B.S., Industrial Engineering, Hacettepe University, Turkey, 2019 - ongoing.
-   Ankara Atatürk High School, Turkey, 2014 - 2019

# *Work Experience*

## Employements

1.  **Türk Havacılık Uzay Sanayii**, Production Planning Candidate Engineer, November 2022 - May 2023

2.  **Hacettepe University**, Part-Time Student, December 2021 - May 2022

## Internships

1.  **ASELSAN**, Project Management Intern, August 2023 - September 2023

2.  **Türk Traktör ve Ziraat Makineleri A.Ş.**, Business Development Intern, July 2023 - August 2023

3.  **Kazan Soda Elektrik A.Ş.**, Logistics Intern, July 2022 - August 2022

# *Projects*

1.  Maintenance Engineering

2.  Lean Production Systems

3.  Optimization and Modeling

4.  Production Planning and Stock Control

5.  Project Management

# *Competencies*

1.  Optimization: Excel Solver

2.  Programming: Python , MATLAB, Microsoft Excel VBA

3.  Design: Solidworks

4.  Other: MS Office

# *Hobbies*

**Basketball Player,** Eryaman Tofaş Basketall Kulübü, 2011 - 2015

**Folk Dances/Modern Dance**, Ankara Atatürk Lisesi Sanat Gecesi, 2015 - 2017
